# architecture
nscalar_invariants: 1
nbasis_tensors: 1
nhlayers:  10
nnodes:  10

# optimization
opt_algorithm: Adam
opt_parameters:
  learning_rate: 0.001
  beta1: 0.9
  beta2: 0.999
  eps: 1.0e-8
opt_restart: 0
opt_steps: 200

# data-preprocessing
preproc_class: Scale

# regularization
regularization:
reg_coeff:

# debug
save_gradients: False
fixed_inputs: False

# save dir
save_dir: results

# training flows and measurements
nflows: 1
parallel: False
flow_0:
  foam_dir: foam_primal
  foam_timedir: 5000
  gradient_method: adjoint
  gradient_options:
    start_from_prev: True
    turb_quant: omega
    foam_dir_a: foam_adjoint 
    foam_timedir_a: 200 
    log_dir: results/foamlogs_flow_0
  nmeasurements: 1
flow_0_measurement_0:
  type: volume
  variable: 'Ux'
  observation_type: point
  point_mask_length: [1.0, 0.02, 1.0] 
  training_data: data/UxPoint_0
  scaling: 1.0 # lambda^2 / sigma^2
