
# architecture
nscalar_invariants: 1
nbasis_tensors: 1
nhlayers:  10
nnodes:  10


# optimization
opt_algorithm: Adam
opt_parameters:
  learning_rate: 0.001
  beta1: 0.9
  beta2: 0.999
  eps: 1.0e-8
opt_restart:   
opt_steps: 1000

# save dir
save_dir: results_1_1

# training data
gtruth: [0.0,]
ndata: 1000
amplitude: 0.0005
data_lim: [-1.0, 2.0]
