#!/bin/sh

cd ${0%/*} || exit 1
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase0
rm -f 0.orig/UForcing 0.orig/pForcing 0.orig/U

#------------------------------------------------------------------------------
