
# architecture
nscalar_invariants: 1
nbasis_tensors: 1
nhlayers:  10
nnodes:  10

# optimization
opt_algorithm: Adam
opt_parameters:
  learning_rate: 0.001
  beta1: 0.9
  beta2: 0.999
  eps: 1.0e-8
opt_restart: 0
opt_steps: 100

# data-preprocessing
preproc_class: Scale

# regularization
regularization:
reg_coeff:

# debug
save_gradients: False
fixed_inputs: False

# save dir
save_dir: results

# training flows and measurements
nflows: 1
parallel: False
flow_0:
  foam_dir: foam_primal
  foam_timedir: 10000
  start_from_prev: True
  turb_quant: omega
  gradient_method: adjoint
  gradient_options:
    foam_dir_a: foam_adjoint 
    foam_timedir_a: 40000 
    log_dir: results/foamlogs_flow_0
  nmeasurements: 8
flow_0_measurement_0:
  type: volume
  variable: 'Ux'
  observation_type: point
  point_mask_length: [0.1, 0.1, 1.0]
  training_data: data/Ux_point_1
  scaling: 1.0
flow_0_measurement_1:
  type: volume
  variable: 'Uy'
  observation_type: point
  point_mask_length: [0.1, 0.1, 1.0]
  training_data: data/Uy_point_1
  scaling: 1.0
flow_0_measurement_2:
  type: volume
  variable: 'Ux'
  observation_type: point
  point_mask_length: [0.1, 0.1, 1.0]
  training_data: data/Ux_point_2
  scaling: 1.0
flow_0_measurement_3:
  type: volume
  variable: 'Uy'
  observation_type: point
  point_mask_length: [0.1, 0.1, 1.0]
  training_data: data/Uy_point_2
  scaling: 1.0
flow_0_measurement_4:
  type: volume
  variable: 'Ux'
  observation_type: point
  point_mask_length: [0.1, 0.1, 1.0]
  training_data: data/Ux_point_3
  scaling: 1.0
flow_0_measurement_5:
  type: volume
  variable: 'Uy'
  observation_type: point
  point_mask_length: [0.1, 0.1, 1.0]
  training_data: data/Uy_point_3
  scaling: 1.0
flow_0_measurement_6:
  type: volume
  variable: 'Ux'
  observation_type: point
  point_mask_length: [0.1, 0.1, 1.0]
  training_data: data/Ux_point_4
  scaling: 1.0
flow_0_measurement_7:
  type: volume
  variable: 'Uy'
  observation_type: point
  point_mask_length: [0.1, 0.1, 1.0]
  training_data: data/Uy_point_4
  scaling: 1.0
